package com.ollie.tierborne.network;
import com.ollie.tierborne.Tierborne; import net.minecraft.resources.ResourceLocation; import net.minecraft.server.level.ServerPlayer; import net.minecraftforge.network.*; import net.minecraftforge.network.simple.SimpleChannel;
public final class ModNetwork {
 private static final String VERSION="1"; public static final SimpleChannel CHANNEL=NetworkRegistry.newSimpleChannel(new ResourceLocation(Tierborne.MOD_ID,"main"),()->VERSION,VERSION::equals,VERSION::equals);
 private ModNetwork(){} public static void register(){int id=0;CHANNEL.registerMessage(id++,ChoosePlayerClassPacket.class,ChoosePlayerClassPacket::encode,ChoosePlayerClassPacket::decode,ChoosePlayerClassPacket::handle);CHANNEL.registerMessage(id++,UnlockSkillPacket.class,UnlockSkillPacket::encode,UnlockSkillPacket::decode,UnlockSkillPacket::handle);CHANNEL.registerMessage(id++,SyncProgressPacket.class,SyncProgressPacket::encode,SyncProgressPacket::decode,SyncProgressPacket::handle);CHANNEL.registerMessage(id++,SelectAlternateAttackPacket.class,SelectAlternateAttackPacket::encode,SelectAlternateAttackPacket::decode,SelectAlternateAttackPacket::handle);CHANNEL.registerMessage(id++,AbilityActionPacket.class,AbilityActionPacket::encode,AbilityActionPacket::decode,AbilityActionPacket::handle);CHANNEL.registerMessage(id++,SyncAbilityStatePacket.class,SyncAbilityStatePacket::encode,SyncAbilityStatePacket::decode,SyncAbilityStatePacket::handle);CHANNEL.registerMessage(id++,SyncCloakStatePacket.class,SyncCloakStatePacket::encode,SyncCloakStatePacket::decode,SyncCloakStatePacket::handle);CHANNEL.registerMessage(id++,SetMovementSpeedLimitPacket.class,SetMovementSpeedLimitPacket::encode,SetMovementSpeedLimitPacket::decode,SetMovementSpeedLimitPacket::handle);CHANNEL.registerMessage(id++,SyncBlockStatePacket.class,SyncBlockStatePacket::encode,SyncBlockStatePacket::decode,SyncBlockStatePacket::handle);CHANNEL.registerMessage(id,SyncUppercutPacket.class,SyncUppercutPacket::encode,SyncUppercutPacket::decode,SyncUppercutPacket::handle);}
 public static void sync(ServerPlayer p){CHANNEL.send(PacketDistributor.PLAYER.with(()->p),SyncProgressPacket.from(p));}
 public static void syncAbilities(ServerPlayer p){CHANNEL.send(PacketDistributor.PLAYER.with(()->p),new SyncAbilityStatePacket(com.ollie.tierborne.combat.AbilityRuntime.statuses(p),com.ollie.tierborne.combat.AbilityRuntime.mainHandCharge(p),com.ollie.tierborne.combat.AbilityRuntime.offhandCharge(p),com.ollie.tierborne.combat.AbilityRuntime.isDualWielding(p),com.ollie.tierborne.combat.AbilityRuntime.isMultislashActive(p),com.ollie.tierborne.combat.FighterCombat.comboBonus(p)));}
 public static void syncCloak(ServerPlayer p,boolean active){CHANNEL.send(PacketDistributor.TRACKING_ENTITY_AND_SELF.with(()->p),new SyncCloakStatePacket(p.getId(),active));}
 public static void syncCloak(ServerPlayer viewer,ServerPlayer target,boolean active){CHANNEL.send(PacketDistributor.PLAYER.with(()->viewer),new SyncCloakStatePacket(target.getId(),active));}
 public static void syncBlock(ServerPlayer p,boolean active){CHANNEL.send(PacketDistributor.TRACKING_ENTITY_AND_SELF.with(()->p),new SyncBlockStatePacket(p.getId(),active));}
 public static void syncBlock(ServerPlayer viewer,ServerPlayer target,boolean active){CHANNEL.send(PacketDistributor.PLAYER.with(()->viewer),new SyncBlockStatePacket(target.getId(),active));}
 public static void syncUppercut(ServerPlayer p,int durationTicks){CHANNEL.send(PacketDistributor.TRACKING_ENTITY_AND_SELF.with(()->p),new SyncUppercutPacket(p.getId(),durationTicks));}
}
