package com.ollie.tierborne.combat;

import com.ollie.tierborne.config.RpgBalanceConfig;
import com.ollie.tierborne.data.*;
import com.ollie.tierborne.playerclass.*;
import net.minecraft.core.BlockPos;
import net.minecraft.network.chat.Component;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.effect.MobEffectInstance;
import net.minecraft.world.effect.MobEffects;
import net.minecraft.world.entity.*;
import net.minecraft.world.entity.Mob;
import net.minecraft.world.damagesource.DamageSource;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.SwordItem;
import net.minecraft.world.item.BowItem;
import net.minecraft.world.item.CrossbowItem;
import net.minecraft.world.item.ArrowItem;
import net.minecraft.world.item.Items;
import net.minecraft.world.entity.projectile.AbstractArrow;
import net.minecraft.world.entity.projectile.Arrow;
import net.minecraft.world.level.ClipContext;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.phys.*;
import java.util.*;

public final class AbilityRuntime {
    private static final String CLOAK_TAG="tierborne:cloak_active";
    private static final Map<UUID, State> STATES=new HashMap<>();
    private static final Set<UUID> INTERNAL_DAMAGE=new HashSet<>();
    private static final Map<UUID, RootState> ROOTED=new HashMap<>();
    private static final Map<RootVisual, Integer> ROOT_VISUALS=new HashMap<>();
    private AbilityRuntime(){}
    public static State state(ServerPlayer p){return STATES.computeIfAbsent(p.getUUID(),u->new State());}
    public static boolean internalDamage(ServerPlayer p){return INTERNAL_DAMAGE.contains(p.getUUID());}
    public static List<AbilityStatus> statuses(ServerPlayer p){
        State s=state(p);long now=p.level.getGameTime();List<AbilityStatus> result=new ArrayList<>();
        for(Map.Entry<String,Long> entry:s.cooldowns.entrySet()){int remaining=(int)Math.max(0,entry.getValue()-now);if(remaining>0)result.add(new AbilityStatus(name(entry.getKey()),remaining,Math.max(1,s.cooldownDurations.getOrDefault(entry.getKey(),remaining)),false,"COOLDOWN"));}
        if(s.multislashActiveUntil>now)result.add(new AbilityStatus("Multislash",(int)(s.multislashActiveUntil-now),Math.max(1,s.multislashDuration),true,"ACTIVE"));
        if(s.cloakedUntil>now)result.add(new AbilityStatus("Cloak",(int)(s.cloakedUntil-now),RpgBalanceConfig.ticks(RpgBalanceConfig.CLOAK_DURATION_SECONDS),true,"ACTIVE"));
        if(s.blocking&&s.blockActiveUntil>now)result.add(new AbilityStatus("Block",(int)(s.blockActiveUntil-now),Math.max(1,s.blockDuration),true,"ACTIVE"));
        if(s.fireballActive){int elapsed=(int)Math.min(s.fireballDuration,Math.max(0,now-s.fireballStarted));result.add(new AbilityStatus("Fireball",s.fireballCharging?elapsed:Math.max(0,s.fireballDuration-elapsed),Math.max(1,s.fireballDuration),true,s.fireballCharging?"CHARGING":"CASTING"));}
        if(s.fireballRecastUntil>now)result.add(new AbilityStatus("Fireball",(int)(s.fireballRecastUntil-now),RpgBalanceConfig.ticks(RpgBalanceConfig.TRIPLE_FIREBALL_RECAST_SECONDS),true,"RECAST"));
        if(s.parryReady>now)result.add(new AbilityStatus("Parry",(int)(s.parryReady-now),RpgBalanceConfig.ticks(RpgBalanceConfig.PARRY_COOLDOWN_SECONDS),false,"COOLDOWN"));
        if(s.utilityReady>now)result.add(new AbilityStatus("Dash",(int)(s.utilityReady-now),Math.max(1,s.utilityDuration),false,"COOLDOWN"));
        if(s.drawLockedUntil>now)result.add(new AbilityStatus("Draw Delay",(int)(s.drawLockedUntil-now),Math.max(1,s.drawLockDuration),false,"RECOVERY"));
        if(s.normalAttackLockedUntil>now&&!progress(p).hasSkill(SwordsmanPlayerClass.HEAVY_RECOVERY))result.add(new AbilityStatus("Attack Recovery",(int)(s.normalAttackLockedUntil-now),Math.max(1,s.normalAttackLockDuration),false,"RECOVERY"));
        if(s.archerMultishotUntil>now)result.add(new AbilityStatus("Multishot",(int)(s.archerMultishotUntil-now),RpgBalanceConfig.ticks(RpgBalanceConfig.MULTISHOT_DELAY_SECONDS),true,"ACTIVE"));
        if(s.fullyChargedReady)result.add(new AbilityStatus("Fully Charged",(int)Math.max(0,s.fullyChargedReadyUntil-now),RpgBalanceConfig.ticks(RpgBalanceConfig.FULLY_CHARGED_READY_WINDOW_SECONDS),true,"READY"));
        if(s.fullyChargedDrawing){int total=fullyChargedDrawTicks(progress(p));int elapsed=(int)Math.max(0,now-s.fullyChargedStarted);result.add(new AbilityStatus("Fully Charged",Math.min(total,elapsed),total,true,"CHARGING"));}
        if(s.backstepRecastUntil>now)result.add(new AbilityStatus("Backstep",(int)(s.backstepRecastUntil-now),RpgBalanceConfig.ticks(RpgBalanceConfig.BACKSTEP_RECAST_SECONDS),true,"RECAST"));
        if(s.rootsActive)result.add(new AbilityStatus("Nature's Roots",(int)Math.max(0,s.rootsUntil-now),RpgBalanceConfig.ticks(RpgBalanceConfig.ROOTS_CHANNEL_SECONDS),true,"CHANNELING"));
        result.addAll(FighterCombat.statuses(p));
        result.sort(Comparator.comparing(AbilityStatus::name));return result;
    }
    public static void input(ServerPlayer p,AbilityAction action){
        PlayerProgress progress=progress(p); State s=state(p); long now=p.level.getGameTime();
        if(CombatControl.offenseDisabled(p))return;
        if(isRooted(p)&&action!=AbilityAction.ALTERNATE_RELEASE)return;
        if(s.fullyChargedDrawing&&action!=AbilityAction.ALTERNATE_RELEASE)return;
        if(s.fireballActive){if(action==AbilityAction.ALTERNATE_RELEASE){s.alternateHeld=false;if(s.fireballCharging)finishFireball(p,progress,s,now);}return;}
        if(action==AbilityAction.ALTERNATE_RELEASE){s.alternateHeld=false;if(s.rootsActive)endRoots(p,s,now);return;}
        if(action==AbilityAction.UTILITY_START){if(isRooted(p))return;if(progress.hasSkill(SwordsmanPlayerClass.DUAL)&&sword(p.getMainHandItem())&&!s.blockExhausted&&s.cooldowns.getOrDefault("block",0L)<=now){s.blockDuration=Math.max(1,RpgBalanceConfig.ticks(RpgBalanceConfig.BLOCK_MAX_DURATION_SECONDS));s.blockActiveUntil=now+s.blockDuration;setBlocking(p,s,true);}if(progress.hasSkill(SwordsmanPlayerClass.SWORDMASTER))dash(p,progress,s,now);else if(ArcherPlayerClass.ID.equals(progress.playerClassId()))archerDash(p,s,now);return;}
        if(action==AbilityAction.UTILITY_STOP){if(s.blocking)endBlock(p,s,now);s.blockExhausted=false;return;}
        if(action==AbilityAction.MAIN_HAND_ATTACK){mainHand(p,progress,s,now);return;}
        if(action==AbilityAction.OFFHAND_ATTACK){offhand(p,progress,s,now);return;}
        if(action!=AbilityAction.ALTERNATE_ATTACK)return;
        AlternateAttackDefinition attack=AlternateAttackDefinition.find(progress.selectedAlternateAttack());
        if(attack==null||!progress.hasSkill(attack.skillId())||s.cooldowns.getOrDefault(attack.id(),0L)>now||s.multislashActiveUntil>now)return;
        if(FighterCombat.input(p,attack.id()))return;
        switch(attack.id()){
            case "dash_strike"->dashStrike(p,progress,s,now);
            case "multislash"->multislash(p,progress,s,now);
            case "heavy_attack"->heavyAttack(p,progress,s,now);
            case "cloak"->cloak(p,s,now);
            case "leap_strike"->leap(p,s,now);
            case "fireball"->startFireball(p,progress,s,now);
            case "flame_slash"->flameSlash(p,progress,s,now);
            case "multishot_bow"->startArcherMultishot(p,s,now);
            case "fully_charged"->startFullyCharged(p,s,now);
            case "elemental_shot"->elementalShot(p,s,now);
            case "backstep"->backstep(p,progress,s,now);
            case "natures_roots"->startRoots(p,s,now);
        }
    }
    public static void tick(ServerPlayer p){
        State s=state(p); long now=p.level.getGameTime(); PlayerProgress progress=progress(p);
        boolean holdingSword=sword(p.getMainHandItem());
        if(progress.hasSkill(SwordsmanPlayerClass.HEAVY)){
            if(holdingSword&&(!s.wasHoldingSword||p.getInventory().selected!=s.lastSelectedSlot||p.getMainHandItem().getItem()!=s.lastMainItem)){s.drawLockDuration=RpgBalanceConfig.ticks(RpgBalanceConfig.HEAVY_DRAW_DELAY_SECONDS);s.drawLockedUntil=now+s.drawLockDuration;}
            if(holdingSword)s.heavyMoveUntil=now+RpgBalanceConfig.ticks(RpgBalanceConfig.HEAVY_MOVE_LINGER_SECONDS);
        }
        s.wasHoldingSword=holdingSword;s.lastMainItem=p.getMainHandItem().getItem();s.lastSelectedSlot=p.getInventory().selected;
        if(s.multislashHitsRemaining>0&&now>=s.nextMultislashHit){boolean offhand=s.multislashUsesOffhand&&s.multislashAnimationIndex%2==1;net.minecraft.world.InteractionHand hand=offhand?net.minecraft.world.InteractionHand.OFF_HAND:net.minecraft.world.InteractionHand.MAIN_HAND;broadcastSwing(p,hand);s.multislashHitsRemaining--;s.multislashAnimationIndex++;if(s.multislashHitsRemaining>0)s.nextMultislashHit=s.multislashStarted+multislashSwingOffset(s.multislashUsesOffhand,s.multislashAnimationIndex);}
        if(s.multislashPendingCooldown&&now>=s.multislashActiveUntil){s.multislashPendingCooldown=false;p.resetAttackStrengthTicker();s.mainLastAttack=now;if(s.multislashUsesOffhand)s.offLastAttack=now;cooldown(s,"multislash",now,RpgBalanceConfig.ticks(RpgBalanceConfig.MULTISLASH_COOLDOWN_SECONDS));}
        if(s.leaping&&p.isOnGround()&&now>s.leapStarted+3){s.leaping=false;double radius=RpgBalanceConfig.LEAP_RADIUS.get();for(LivingEntity target:p.level.getEntitiesOfClass(LivingEntity.class,p.getBoundingBox().inflate(radius),e->e!=p&&e.isAlive())){hurt(p,target,baseDamage(p));Vec3 away=target.position().subtract(p.position()).normalize().scale(RpgBalanceConfig.LEAP_KNOCKBACK.get());target.push(away.x,0.45,away.z);}}
        if(s.cloakedUntil>0&&now>=s.cloakedUntil)endCloak(p,s,now);
        if(s.cloakedUntil>now)for(Mob mob:p.level.getEntitiesOfClass(Mob.class,p.getBoundingBox().inflate(32),m->m.getTarget()==p))mob.setTarget(null);
        if(progress.hasSkill(SwordsmanPlayerClass.ROGUE)&&now%20==0)preferOtherTargets(p);
        if(s.blocking&&now>=s.blockActiveUntil){endBlock(p,s,now);s.blockExhausted=true;}
        if(s.fireballActive){castParticles(p,s,now);if(!s.fireballCharging&&now-s.fireballStarted>=s.fireballDuration)finishFireball(p,progress,s,now);}
        if(s.fireballRecastUntil>0&&now>=s.fireballRecastUntil)finishFireballSequence(p,s,now);
        if(s.blocking&&(!progress.hasSkill(SwordsmanPlayerClass.DUAL)||!sword(p.getMainHandItem()))){endBlock(p,s,now);s.blockExhausted=true;}
        if(s.archerMultishotUntil>0&&now>=s.archerMultishotUntil){shootAbilityArrow(p,false,true);s.archerMultishotUntil=0;cooldown(s,"multishot_bow",now,RpgBalanceConfig.ticks(RpgBalanceConfig.MULTISHOT_COOLDOWN_SECONDS));}
        if(s.backstepRecastUntil>0&&now>=s.backstepRecastUntil){s.backstepRecastUntil=0;cooldown(s,"backstep",now,RpgBalanceConfig.ticks(RpgBalanceConfig.BACKSTEP_COOLDOWN_SECONDS));}
        if(s.rootsActive){LivingEntity victim=rootVictim(p,s);if(now>=s.rootsUntil||victim==null||!victim.isAlive())endRoots(p,s,now);else{holdRooted(p);holdRooted(victim);rootsParticles(victim);}}
        if(s.fullyChargedReady&&now>=s.fullyChargedReadyUntil)consumeFullyCharged(p,s,now);
        if(s.fullyChargedDrawing&&p.isUsingItem()&&p.getUseItem()!=s.fullyChargedWeapon)consumeFullyCharged(p,s,now);
        else if(s.fullyChargedDrawing&&!p.isUsingItem()){if(s.fullyChargedCancelAt==0)s.fullyChargedCancelAt=now+2;else if(now>=s.fullyChargedCancelAt)consumeFullyCharged(p,s,now);}else if(s.fullyChargedDrawing)s.fullyChargedCancelAt=0;
        tickRooted(p.level,now);
        FighterCombat.tick(p);
    }
    public static boolean normalAttackBlocked(ServerPlayer p){State s=state(p);long now=p.level.getGameTime();return isRooted(p)||s.fireballActive||now<s.multislashActiveUntil||now<s.drawLockedUntil||(now<s.normalAttackLockedUntil&&!progress(p).hasSkill(SwordsmanPlayerClass.HEAVY_RECOVERY));}
    public static boolean beginNormalSwordAttack(ServerPlayer p){if(normalAttackBlocked(p))return false;state(p).mainLastAttack=p.level.getGameTime();return true;}
    public static void offensiveAction(ServerPlayer p){State s=state(p);if(s.cloakedUntil>0)endCloak(p,s,p.level.getGameTime());}
    public static boolean isCloaked(ServerPlayer p){return state(p).cloakedUntil>p.level.getGameTime();}
    public static boolean isBlocking(ServerPlayer p){return state(p).blocking;}
    public static boolean isDualWielding(ServerPlayer p){PlayerProgress x=progress(p);return x.hasSkill(SwordsmanPlayerClass.DUAL)&&sword(p.getMainHandItem())&&sword(p.getOffhandItem())||x.hasSkill(FighterPlayerClass.MONK)&&FighterStats.isFist(p);}
    public static boolean isMultislashActive(ServerPlayer p){return state(p).multislashActiveUntil>p.level.getGameTime();}
    public static void cancelFireball(ServerPlayer p){State s=state(p);s.fireballActive=false;s.fireballCharging=false;s.fireballRecastUntil=0;s.fireballShots=0;}
    public static float mainHandCharge(ServerPlayer p){State s=state(p);long now=p.level.getGameTime();return s.mainLastAttack==Long.MIN_VALUE?1.0F:(float)Math.min(1.0,(now-s.mainLastAttack)/(double)recharge(p));}
    public static float offhandCharge(ServerPlayer p){State s=state(p);long now=p.level.getGameTime();return s.offLastAttack==Long.MIN_VALUE?1.0F:(float)Math.min(1.0,(now-s.offLastAttack)/(double)recharge(p));}
    public static void resetTransient(ServerPlayer p){State s=STATES.get(p.getUUID());if(s!=null&&s.rootsTarget!=null)removeRoot(s.rootsTarget);removeRoot(p.getUUID());STATES.remove(p.getUUID());FighterCombat.reset(p);if(p.getPersistentData().getBoolean(CLOAK_TAG)){p.removeEffect(MobEffects.INVISIBILITY);p.getPersistentData().remove(CLOAK_TAG);}com.ollie.tierborne.network.ModNetwork.syncCloak(p,false);com.ollie.tierborne.network.ModNetwork.syncBlock(p,false);com.ollie.tierborne.network.ModNetwork.syncAbilities(p);}
    public static boolean heavyMovementPenaltyActive(ServerPlayer p){return p.level.getGameTime()<state(p).heavyMoveUntil;}
    public static void tryParry(ServerPlayer p,Entity attacker){PlayerProgress x=progress(p);State s=state(p);long now=p.level.getGameTime();if(!x.hasSkill(SwordsmanPlayerClass.PARRY)||now<s.parryReady||!(attacker instanceof LivingEntity target)||!sword(p.getMainHandItem())||!sword(p.getOffhandItem()))return;s.parryReady=now+RpgBalanceConfig.ticks(RpgBalanceConfig.PARRY_COOLDOWN_SECONDS);hurt(p,target,baseDamage(p));hurt(p,target,baseDamage(p));}
    public static double additionalSwordDamagePercent(ServerPlayer p,LivingEntity target){
        PlayerProgress x=progress(p);double bonus=SwordsmanStats.subclassSwordDamage(x.unlockedSkills());
        if(x.hasSkill(SwordsmanPlayerClass.ROGUE)){
            long now=p.level.getGameTime();State s=state(p);
            if(x.hasSkill(SwordsmanPlayerClass.BACKSTAB)){Vec3 toAttacker=p.position().subtract(target.position()).normalize();if(target.getLookAngle().dot(toAttacker)<-RpgBalanceConfig.BACKSTAB_DOT_THRESHOLD.get())bonus+=RpgBalanceConfig.BACKSTAB_DAMAGE.get();}
            Long lastHit=s.lastHit.get(target.getUUID());
            if(x.hasSkill(SwordsmanPlayerClass.FIRST_HIT)&&(lastHit==null||now-lastHit>RpgBalanceConfig.ticks(RpgBalanceConfig.FIRST_HIT_RESET_SECONDS)))bonus+=RpgBalanceConfig.FIRST_HIT_DAMAGE.get();
            if(x.hasSkill(SwordsmanPlayerClass.NON_AGGRO)&&target instanceof Mob mob&&mob.getTarget()!=p)bonus+=RpgBalanceConfig.NON_AGGRO_DAMAGE.get();
            s.lastHit.put(target.getUUID(),now);
        }
        return bonus;
    }
    private static void dashStrike(ServerPlayer p,PlayerProgress x,State s,long now){if(!sword(p.getMainHandItem()))return;offensiveAction(p);boolean swordmaster=x.hasSkill(SwordsmanPlayerClass.SWORDMASTER);double distance=swordmaster&&x.hasSkill(SwordsmanPlayerClass.DASH_DISTANCE)?RpgBalanceConfig.DASH_STRIKE_UPGRADED_DISTANCE.get():RpgBalanceConfig.DASH_STRIKE_DISTANCE.get();Vec3 look=horizontal(p.getLookAngle());p.setDeltaMovement(look.scale(1.5*distance/RpgBalanceConfig.DASH_STRIKE_DISTANCE.get()).add(0,0.1,0));p.hurtMarked=true;p.swing(net.minecraft.world.InteractionHand.MAIN_HAND,true);double bonus=swordmaster&&x.hasSkill(SwordsmanPlayerClass.SM_DASH_STRIKE)?RpgBalanceConfig.DASH_STRIKE_UPGRADE_DAMAGE.get():RpgBalanceConfig.DASH_STRIKE_DAMAGE.get();target(p,distance).ifPresent(t->weaponHit(p,t,p.getMainHandItem(),net.minecraft.world.InteractionHand.MAIN_HAND,fullChargeDamage(p,p.getMainHandItem(),t)*(1+bonus/100),false));double seconds=swordmaster&&x.hasSkill(SwordsmanPlayerClass.DASH_COOLDOWN)?RpgBalanceConfig.DASH_STRIKE_UPGRADED_COOLDOWN_SECONDS.get():RpgBalanceConfig.DASH_STRIKE_COOLDOWN_SECONDS.get();cooldown(s,"dash_strike",now,RpgBalanceConfig.ticksValue(seconds));}
    private static void heavyAttack(ServerPlayer p,PlayerProgress x,State s,long now){if(!sword(p.getMainHandItem()))return;offensiveAction(p);p.swing(net.minecraft.world.InteractionHand.MAIN_HAND,true);double bonus=x.hasSkill(SwordsmanPlayerClass.HEAVY_ATTACK_DAMAGE)?RpgBalanceConfig.HEAVY_ATTACK_UPGRADE_DAMAGE.get():RpgBalanceConfig.HEAVY_ATTACK_DAMAGE.get();target(p,reach(x)).ifPresent(t->weaponHit(p,t,p.getMainHandItem(),net.minecraft.world.InteractionHand.MAIN_HAND,fullChargeDamage(p,p.getMainHandItem(),t)*(1+bonus/100),false));int cd=RpgBalanceConfig.ticks(x.hasSkill(SwordsmanPlayerClass.HEAVY_ATTACK_COOLDOWN)?RpgBalanceConfig.HEAVY_ATTACK_UPGRADE_COOLDOWN_SECONDS:RpgBalanceConfig.HEAVY_ATTACK_COOLDOWN_SECONDS);cooldown(s,"heavy_attack",now,cd);if(!x.hasSkill(SwordsmanPlayerClass.HEAVY_RECOVERY)){s.normalAttackLockDuration=cd;s.normalAttackLockedUntil=now+cd;}}
    private static void multislash(ServerPlayer p,PlayerProgress x,State s,long now){if(!sword(p.getMainHandItem())){p.displayClientMessage(Component.literal("Multislash requires a sword in the main hand."),true);return;}offensiveAction(p);s.multislashUsesOffhand=sword(p.getOffhandItem());boolean hit=false;for(LivingEntity target:multislashTargets(p))hit|=multislashHit(p,target,s.multislashUsesOffhand);if(hit){damageWeapon(p,p.getMainHandItem(),net.minecraft.world.InteractionHand.MAIN_HAND,2);if(s.multislashUsesOffhand)damageWeapon(p,p.getOffhandItem(),net.minecraft.world.InteractionHand.OFF_HAND,2);}s.multislashHitsRemaining=s.multislashUsesOffhand?4:2;s.multislashAnimationIndex=0;s.multislashStarted=now;s.multislashDuration=Math.max(1,RpgBalanceConfig.ticks(RpgBalanceConfig.MULTISLASH_DURATION_SECONDS));s.nextMultislashHit=now;s.multislashActiveUntil=now+s.multislashDuration;s.multislashPendingCooldown=true;}
    private static void startFireball(ServerPlayer p,PlayerProgress x,State s,long now){if(!sword(p.getMainHandItem())){p.displayClientMessage(Component.literal("Fireball requires a sword in the main hand."),true);return;}offensiveAction(p);if(s.fireballRecastUntil>now&&s.fireballShots>0){launchFireball(p,x,s.fireballSequenceCharge);s.fireballShots++;if(s.fireballShots>=3)finishFireballSequence(p,s,now);else s.fireballRecastUntil=now+RpgBalanceConfig.ticks(RpgBalanceConfig.TRIPLE_FIREBALL_RECAST_SECONDS);return;}if(s.blocking){endBlock(p,s,now);s.blockExhausted=true;}s.alternateHeld=true;s.fireballActive=true;s.fireballCharging=x.hasSkill(SwordsmanPlayerClass.FIREBALL_CHARGE);s.fireballStarted=now;s.fireballDuration=Math.max(1,RpgBalanceConfig.ticks(s.fireballCharging?RpgBalanceConfig.FIREBALL_MAX_CHARGE_SECONDS:RpgBalanceConfig.FIREBALL_CAST_SECONDS));p.level.playSound(null,p.blockPosition(),net.minecraft.sounds.SoundEvents.FIRECHARGE_USE,net.minecraft.sounds.SoundSource.PLAYERS,0.55F,1.35F);}
    private static void finishFireball(ServerPlayer p,PlayerProgress x,State s,long now){if(!s.fireballActive)return;double minimumCharge=RpgBalanceConfig.FIREBALL_MIN_CHARGE_PERCENT.get()/100.0;double charge=s.fireballCharging?Math.min(1.0,Math.max(minimumCharge,(now-s.fireballStarted)/(double)Math.max(1,s.fireballDuration))):1.0;s.fireballActive=false;s.fireballCharging=false;launchFireball(p,x,charge);if(x.hasSkill(SwordsmanPlayerClass.TRIPLE_FIREBALL)){s.fireballSequenceCharge=charge;s.fireballShots=1;s.fireballRecastUntil=now+RpgBalanceConfig.ticks(RpgBalanceConfig.TRIPLE_FIREBALL_RECAST_SECONDS);}else cooldown(s,"fireball",now,fireballCooldownTicks(x));}
    private static void launchFireball(ServerPlayer p,PlayerProgress x,double charge){double damageScale=fireballDamageScale(x,charge);double damage=baseDamage(p)*damageScale;float speed=(float)(fireballSpeed(x)/20.0);com.ollie.tierborne.entity.FireballProjectile projectile=new com.ollie.tierborne.entity.FireballProjectile(p,(float)damage,(float)damageScale,(float)charge,speed);p.level.addFreshEntity(projectile);}
    private static double fireballDamageScale(PlayerProgress x,double charge){double minimum=RpgBalanceConfig.FIREBALL_MIN_CHARGE_PERCENT.get()/100.0;double minDamage=RpgBalanceConfig.FIREBALL_MIN_DAMAGE_PERCENT.get()/100.0,maxDamage=RpgBalanceConfig.FIREBALL_MAX_DAMAGE_PERCENT.get()/100.0;double normalized=(charge-minimum)/Math.max(0.0001,1.0-minimum);double chargeMultiplier=charge>=0.999?maxDamage:minDamage+(maxDamage-minDamage)*net.minecraft.util.Mth.clamp(normalized,0.0,1.0);double swordBonus=x.totalBonus(SkillBonusType.SWORD_DAMAGE)+SwordsmanStats.subclassSwordDamage(x.unlockedSkills());return(1.0+swordBonus/100.0)*fireballDamagePercent(x)/100.0*chargeMultiplier;}
    private static void finishFireballSequence(ServerPlayer p,State s,long now){if(s.fireballShots<=0)return;s.fireballRecastUntil=0;s.fireballShots=0;s.fireballSequenceCharge=0;cooldown(s,"fireball",now,fireballCooldownTicks(progress(p)));}
    private static void flameSlash(ServerPlayer p,PlayerProgress x,State s,long now){if(!sword(p.getMainHandItem())){p.displayClientMessage(Component.literal("Flame Slash requires a sword in the main hand."),true);return;}offensiveAction(p);double scale=fireballDamageScale(x,1.0);com.ollie.tierborne.entity.FlameSlashProjectile slash=new com.ollie.tierborne.entity.FlameSlashProjectile(p,(float)(2.0*baseDamage(p)*scale),(float)(2.0*scale));p.level.addFreshEntity(slash);broadcastSwing(p,net.minecraft.world.InteractionHand.MAIN_HAND);cooldown(s,"flame_slash",now,RpgBalanceConfig.ticks(RpgBalanceConfig.FLAME_SLASH_COOLDOWN_SECONDS));}
    private static void castParticles(ServerPlayer p,State s,long now){if(!(p.level instanceof net.minecraft.server.level.ServerLevel level)||now%2!=0)return;double progress=Math.min(1.0,(now-s.fireballStarted)/(double)Math.max(1,s.fireballDuration));Vec3 hand=p.getEyePosition().add(p.getLookAngle().scale(0.55)).add(0,-0.28,0);int minimum=RpgBalanceConfig.FIREBALL_MIN_CORE_PARTICLES.get(),maximum=RpgBalanceConfig.FIREBALL_MAX_CORE_PARTICLES.get();int flames=(int)Math.round(minimum+(maximum-minimum)*progress);double minRadius=RpgBalanceConfig.FIREBALL_MIN_PARTICLE_RADIUS.get(),maxRadius=RpgBalanceConfig.FIREBALL_MAX_PARTICLE_RADIUS.get();double radius=minRadius+(maxRadius-minRadius)*progress;level.sendParticles(net.minecraft.core.particles.ParticleTypes.FLAME,hand.x,hand.y,hand.z,flames,radius,radius,radius,0.01);if(progress>0.35){int smoke=Math.max(1,(int)Math.round(RpgBalanceConfig.FIREBALL_MAX_TRAIL_PARTICLES.get()*progress));level.sendParticles(net.minecraft.core.particles.ParticleTypes.SMOKE,hand.x,hand.y,hand.z,smoke,radius*.65,radius*.65,radius*.65,0.005);}}
    private static void cloak(ServerPlayer p,State s,long now){int duration=RpgBalanceConfig.ticks(RpgBalanceConfig.CLOAK_DURATION_SECONDS);p.addEffect(new MobEffectInstance(MobEffects.INVISIBILITY,duration,0,false,false,true));p.getPersistentData().putBoolean(CLOAK_TAG,true);s.cloakedUntil=now+duration;com.ollie.tierborne.network.ModNetwork.syncCloak(p,true);for(Mob mob:p.level.getEntitiesOfClass(Mob.class,p.getBoundingBox().inflate(32),m->m.getTarget()==p))mob.setTarget(null);}
    private static void endCloak(ServerPlayer p,State s,long now){if(s.cloakedUntil<=0)return;s.cloakedUntil=0;p.removeEffect(MobEffects.INVISIBILITY);p.getPersistentData().remove(CLOAK_TAG);com.ollie.tierborne.network.ModNetwork.syncCloak(p,false);cooldown(s,"cloak",now,RpgBalanceConfig.ticks(RpgBalanceConfig.CLOAK_COOLDOWN_SECONDS));}
    private static void leap(ServerPlayer p,State s,long now){offensiveAction(p);p.setDeltaMovement(p.getDeltaMovement().x,RpgBalanceConfig.LEAP_LAUNCH.get(),p.getDeltaMovement().z);p.hurtMarked=true;s.leaping=true;s.leapStarted=now;cooldown(s,"leap_strike",now,RpgBalanceConfig.ticks(RpgBalanceConfig.LEAP_COOLDOWN_SECONDS));}
    private static void dash(ServerPlayer p,PlayerProgress x,State s,long now){if(now<s.utilityReady)return;boolean upgraded=x.hasSkill(SwordsmanPlayerClass.SM_DASH);Vec3 look=horizontal(p.getLookAngle());p.setDeltaMovement(look.scale(upgraded?RpgBalanceConfig.DASH_UPGRADE_VELOCITY.get():RpgBalanceConfig.DASH_VELOCITY.get()).add(0,0.08,0));p.hurtMarked=true;s.utilityDuration=RpgBalanceConfig.ticks(upgraded?RpgBalanceConfig.DASH_UPGRADE_COOLDOWN_SECONDS:RpgBalanceConfig.DASH_COOLDOWN_SECONDS);s.utilityReady=now+s.utilityDuration;}
    private static void mainHand(ServerPlayer p,PlayerProgress x,State s,long now){boolean dualSwords=x.hasSkill(SwordsmanPlayerClass.DUAL)&&sword(p.getMainHandItem())&&sword(p.getOffhandItem());boolean monkFists=x.hasSkill(FighterPlayerClass.MONK)&&FighterStats.isFist(p);if((!dualSwords&&!monkFists)||normalAttackBlocked(p))return;offensiveAction(p);double charge=s.mainLastAttack==Long.MIN_VALUE?1.0:Math.min(1.0,(now-s.mainLastAttack)/(double)recharge(p));double strength=0.2+charge*charge*0.8;Optional<LivingEntity> target=target(p,3.2);p.swing(net.minecraft.world.InteractionHand.MAIN_HAND,true);if(target.isPresent()&&weaponHit(p,target.get(),p.getMainHandItem(),net.minecraft.world.InteractionHand.MAIN_HAND,fullChargeDamage(p,p.getMainHandItem(),target.get())*strength,true))s.mainLastAttack=now;}
    private static void offhand(ServerPlayer p,PlayerProgress x,State s,long now){boolean dualSwords=x.hasSkill(SwordsmanPlayerClass.DUAL)&&sword(p.getMainHandItem())&&sword(p.getOffhandItem());boolean monkFists=x.hasSkill(FighterPlayerClass.MONK)&&FighterStats.isFist(p);if((!dualSwords&&!monkFists)||normalAttackBlocked(p))return;offensiveAction(p);long recharge=recharge(p);double charge=s.offLastAttack==Long.MIN_VALUE?1.0:Math.min(1.0,(now-s.offLastAttack)/(double)recharge);double strength=0.2+charge*charge*0.8;Optional<LivingEntity> target=target(p,3.2);p.swing(net.minecraft.world.InteractionHand.OFF_HAND,true);if(target.isPresent()&&weaponHit(p,target.get(),p.getOffhandItem(),net.minecraft.world.InteractionHand.OFF_HAND,fullChargeDamage(p,p.getOffhandItem(),target.get())*strength,true))s.offLastAttack=now;}
    private static boolean multislashHit(ServerPlayer p,LivingEntity target,boolean useOffhand){ItemStack main=p.getMainHandItem(),off=p.getOffhandItem();double damage=2.0*fullChargeDamage(p,main,target);if(useOffhand)damage+=2.0*fullChargeDamage(p,off,target);if(!hurt(p,target,damage))return false;applyWeaponEffects(p,target,main);if(useOffhand)applyWeaponEffects(p,target,off);return true;}
    private static List<LivingEntity> multislashTargets(ServerPlayer p){double range=3.5+RpgBalanceConfig.MULTISLASH_BONUS_RANGE.get(),halfWidth=RpgBalanceConfig.MULTISLASH_SWEEP_WIDTH.get()/2.0,halfHeight=RpgBalanceConfig.MULTISLASH_SWEEP_HEIGHT.get()/2.0;Vec3 origin=p.getEyePosition().add(0,-0.5,0),forward=horizontal(p.getLookAngle());AABB search=p.getBoundingBox().expandTowards(forward.scale(range)).inflate(halfWidth,halfHeight,halfWidth);return p.level.getEntitiesOfClass(LivingEntity.class,search,e->{if(e==p||!e.isAlive())return false;Vec3 center=e.getBoundingBox().getCenter(),relative=center.subtract(origin);double ahead=relative.dot(forward);if(ahead<0||ahead>range+e.getBbWidth()/2.0||Math.abs(relative.y)>halfHeight+e.getBbHeight()/2.0)return false;Vec3 lateral=relative.subtract(forward.scale(ahead));if(lateral.horizontalDistance()>halfWidth+e.getBbWidth()/2.0)return false;HitResult obstruction=p.level.clip(new ClipContext(p.getEyePosition(),center,ClipContext.Block.COLLIDER,ClipContext.Fluid.NONE,p));return obstruction.getType()==HitResult.Type.MISS||obstruction.getLocation().distanceToSqr(p.getEyePosition())>=center.distanceToSqr(p.getEyePosition());});}
    private static int multislashSwingOffset(boolean offhand,int index){if(!offhand)return index==1?RpgBalanceConfig.ticksValue(0.60):0;return switch(index){case 1->RpgBalanceConfig.ticks(RpgBalanceConfig.MULTISLASH_OFFHAND_SWING_I_SECONDS);case 2->RpgBalanceConfig.ticks(RpgBalanceConfig.MULTISLASH_MAIN_SWING_II_SECONDS);default->RpgBalanceConfig.ticks(RpgBalanceConfig.MULTISLASH_OFFHAND_SWING_II_SECONDS);};}
    private static void applyWeaponEffects(ServerPlayer p,LivingEntity target,ItemStack weapon){int fire=net.minecraft.world.item.enchantment.EnchantmentHelper.getItemEnchantmentLevel(net.minecraft.world.item.enchantment.Enchantments.FIRE_ASPECT,weapon);if(fire>0)target.setSecondsOnFire(Math.max(target.getRemainingFireTicks()/20,fire*4));int knockback=net.minecraft.world.item.enchantment.EnchantmentHelper.getItemEnchantmentLevel(net.minecraft.world.item.enchantment.Enchantments.KNOCKBACK,weapon);if(knockback>0)target.knockback(knockback*0.5,net.minecraft.util.Mth.sin(p.getYRot()*(float)Math.PI/180.0F),-net.minecraft.util.Mth.cos(p.getYRot()*(float)Math.PI/180.0F));}
    private static void damageWeapon(ServerPlayer p,ItemStack weapon,net.minecraft.world.InteractionHand hand,int hits){for(int i=0;i<hits&&!weapon.isEmpty();i++)weapon.hurtAndBreak(1,p,owner->owner.broadcastBreakEvent(hand));}
    private static void setBlocking(ServerPlayer p,State s,boolean blocking){if(s.blocking==blocking)return;s.blocking=blocking;com.ollie.tierborne.network.ModNetwork.syncBlock(p,blocking);}
    private static void endBlock(ServerPlayer p,State s,long now){if(!s.blocking)return;setBlocking(p,s,false);cooldown(s,"block",now,RpgBalanceConfig.ticks(RpgBalanceConfig.BLOCK_COOLDOWN_SECONDS));}
    private static void broadcastSwing(ServerPlayer player,net.minecraft.world.InteractionHand hand){int animation=hand==net.minecraft.world.InteractionHand.MAIN_HAND?0:3;if(player.level instanceof ServerLevel level)level.getChunkSource().broadcastAndSend(player,new net.minecraft.network.protocol.game.ClientboundAnimatePacket(player,animation));}
    private static boolean hurt(ServerPlayer p,LivingEntity target,double amount){INTERNAL_DAMAGE.add(p.getUUID());try{return target.hurt(DamageSource.playerAttack(p),(float)amount);}finally{INTERNAL_DAMAGE.remove(p.getUUID());}}
    private static boolean weaponHit(ServerPlayer p,LivingEntity target,ItemStack weapon,net.minecraft.world.InteractionHand hand,double amount,boolean bypassHurtFrames){if(bypassHurtFrames)target.invulnerableTime=0;if(!hurt(p,target,amount))return false;int fire=net.minecraft.world.item.enchantment.EnchantmentHelper.getItemEnchantmentLevel(net.minecraft.world.item.enchantment.Enchantments.FIRE_ASPECT,weapon);if(fire>0)target.setSecondsOnFire(fire*4);int knockback=net.minecraft.world.item.enchantment.EnchantmentHelper.getItemEnchantmentLevel(net.minecraft.world.item.enchantment.Enchantments.KNOCKBACK,weapon)+(p.isSprinting()?1:0);if(knockback>0)target.knockback(knockback*0.5,net.minecraft.util.Mth.sin(p.getYRot()*(float)Math.PI/180.0F),-net.minecraft.util.Mth.cos(p.getYRot()*(float)Math.PI/180.0F));weapon.hurtAndBreak(1,p,owner->owner.broadcastBreakEvent(hand));return true;}
    private static Optional<LivingEntity> target(ServerPlayer p,double distance){Vec3 start=p.getEyePosition(),end=start.add(p.getLookAngle().scale(distance));AABB box=p.getBoundingBox().expandTowards(p.getLookAngle().scale(distance)).inflate(1);return p.level.getEntitiesOfClass(LivingEntity.class,box,e->e!=p&&e.isAlive()).stream().filter(e->e.getBoundingBox().inflate(.3).clip(start,end).isPresent()).min(Comparator.comparingDouble(p::distanceToSqr));}
    private static double baseDamage(ServerPlayer p){return p.getAttributeValue(net.minecraft.world.entity.ai.attributes.Attributes.ATTACK_DAMAGE);}
    private static double fullChargeDamage(ServerPlayer p,ItemStack weapon,LivingEntity target){double damage=baseDamage(p);if(weapon!=p.getMainHandItem()&&weapon.getItem() instanceof SwordItem off&&p.getMainHandItem().getItem() instanceof SwordItem main)damage+=off.getDamage()-main.getDamage();return damage+net.minecraft.world.item.enchantment.EnchantmentHelper.getDamageBonus(weapon,target.getMobType());}
    private static double reach(PlayerProgress x){return 3.5+(x.hasSkill(SwordsmanPlayerClass.HEAVY_RANGE)?RpgBalanceConfig.HEAVY_RANGE.get():0);}
    private static long recharge(ServerPlayer p){return Math.max(1,Math.round(20.0/Math.max(0.1,p.getAttributeValue(net.minecraft.world.entity.ai.attributes.Attributes.ATTACK_SPEED))));}
    private static boolean sword(ItemStack s){return s.getItem() instanceof SwordItem;}
    private static Vec3 horizontal(Vec3 v){Vec3 h=new Vec3(v.x,0,v.z);return h.lengthSqr()==0?Vec3.ZERO:h.normalize();}
    private static PlayerProgress progress(ServerPlayer p){return PlayerProgressSavedData.get(p.getServer()).get(p.getUUID());}
    private static double fireballSpeed(PlayerProgress progress){return progress.hasSkill(SwordsmanPlayerClass.FIREBALL_SPEED_II)?RpgBalanceConfig.FIREBALL_SPEED_II.get():progress.hasSkill(SwordsmanPlayerClass.FIREBALL_SPEED_I)?RpgBalanceConfig.FIREBALL_SPEED_I.get():RpgBalanceConfig.FIREBALL_BASE_SPEED.get();}
    private static double fireballDamagePercent(PlayerProgress progress){return progress.hasSkill(SwordsmanPlayerClass.FIREBALL_DAMAGE_II)?RpgBalanceConfig.FIREBALL_DAMAGE_II.get():progress.hasSkill(SwordsmanPlayerClass.FIREBALL_DAMAGE_I)?RpgBalanceConfig.FIREBALL_DAMAGE_I.get():RpgBalanceConfig.FIREBALL_DAMAGE_PERCENT.get();}
    private static int fireballCooldownTicks(PlayerProgress progress){return RpgBalanceConfig.ticks(progress.hasSkill(SwordsmanPlayerClass.FIREBALL_COOLDOWN)?RpgBalanceConfig.FIREBALL_UPGRADED_COOLDOWN_SECONDS:RpgBalanceConfig.FIREBALL_COOLDOWN_SECONDS);}
    private static void archerDash(ServerPlayer p,State s,long now){if(now<s.utilityReady)return;Vec3 direction=horizontal(p.getLookAngle());p.setDeltaMovement(direction.scale(RpgBalanceConfig.ARCHER_DASH_VELOCITY.get()).add(0,.08,0));p.hurtMarked=true;s.utilityDuration=RpgBalanceConfig.ticks(RpgBalanceConfig.ARCHER_DASH_COOLDOWN_SECONDS);s.utilityReady=now+s.utilityDuration;}
    private static void startArcherMultishot(ServerPlayer p,State s,long now){ItemStack weapon=rangedWeapon(p,true);if(weapon.isEmpty()||!CrossbowItem.isCharged(weapon)){p.displayClientMessage(Component.literal("Multishot requires a fully charged crossbow."),true);return;}shootAbilityArrow(p,true,true);CrossbowItem.setCharged(weapon,false);weapon.getOrCreateTag().remove("ChargedProjectiles");s.archerMultishotUntil=now+Math.max(1,RpgBalanceConfig.ticks(RpgBalanceConfig.MULTISHOT_DELAY_SECONDS));}
    private static void startFullyCharged(ServerPlayer p,State s,long now){s.fullyChargedReady=true;s.fullyChargedDrawing=false;s.fullyChargedReadyUntil=now+RpgBalanceConfig.ticks(RpgBalanceConfig.FULLY_CHARGED_READY_WINDOW_SECONDS);s.fullyChargedStarted=0;s.fullyChargedCancelAt=0;s.bowDelayAccumulator=0;}
    private static void elementalShot(ServerPlayer p,State s,long now){s.elementalNextArrow=true;if(shootAbilityArrow(p,false,false))cooldown(s,"elemental_shot",now,RpgBalanceConfig.ticks(RpgBalanceConfig.ELEMENTAL_SHOT_COOLDOWN_SECONDS));else s.elementalNextArrow=false;}
    private static void backstep(ServerPlayer p,PlayerProgress progress,State s,long now){if(s.backstepRecastUntil>now){moveBackstep(p,progress);shootAbilityArrow(p,false,false);s.backstepRecastUntil=0;cooldown(s,"backstep",now,RpgBalanceConfig.ticks(RpgBalanceConfig.BACKSTEP_COOLDOWN_SECONDS));return;}if(!shootAbilityArrow(p,false,false))return;moveBackstep(p,progress);if(progress.hasSkill(ArcherPlayerClass.BACKSTEP_DOUBLE))s.backstepRecastUntil=now+RpgBalanceConfig.ticks(RpgBalanceConfig.BACKSTEP_RECAST_SECONDS);else cooldown(s,"backstep",now,RpgBalanceConfig.ticks(RpgBalanceConfig.BACKSTEP_COOLDOWN_SECONDS));}
    private static void moveBackstep(ServerPlayer p,PlayerProgress progress){double distance=progress.hasSkill(ArcherPlayerClass.BACKSTEP_RANGE)?RpgBalanceConfig.BACKSTEP_UPGRADED_DISTANCE.get():RpgBalanceConfig.BACKSTEP_DISTANCE.get();Vec3 direction=horizontal(p.getLookAngle()).scale(-1);if(progress.hasSkill(ArcherPlayerClass.BACKSTEP_DIRECTIONAL)&&(Math.abs(p.xxa)+Math.abs(p.zza)>.05)){Vec3 forward=horizontal(p.getLookAngle()),right=new Vec3(-forward.z,0,forward.x);direction=forward.scale(p.zza).add(right.scale(p.xxa)).normalize();}p.setDeltaMovement(direction.scale(distance/4.0).add(0,.08,0));p.hurtMarked=true;}
    private static void startRoots(ServerPlayer p,State s,long now){Optional<LivingEntity> victim=lineOfSightTarget(p,RpgBalanceConfig.ROOTS_RANGE.get());if(victim.isEmpty())return;s.rootsActive=true;s.rootsTarget=victim.get().getUUID();s.rootsUntil=now+RpgBalanceConfig.ticks(RpgBalanceConfig.ROOTS_CHANNEL_SECONDS);putRoot(p,s.rootsUntil);putRoot(victim.get(),s.rootsUntil);}
    private static void endRoots(ServerPlayer p,State s,long now){if(!s.rootsActive)return;LivingEntity victim=rootVictim(p,s);s.rootsActive=false;removeRoot(p.getUUID());if(victim!=null){RootState current=ROOTED.get(victim.getUUID());long until=now+RpgBalanceConfig.ticks(RpgBalanceConfig.ROOTS_TAIL_SECONDS);if(current!=null)ROOTED.put(victim.getUUID(),new RootState(current.entity,current.anchor,until,current.grassBase));else putRoot(victim,until);}s.rootsTarget=null;cooldown(s,"natures_roots",now,RpgBalanceConfig.ticks(RpgBalanceConfig.ROOTS_COOLDOWN_SECONDS));}
    private static LivingEntity rootVictim(ServerPlayer p,State s){return s.rootsTarget!=null&&p.level instanceof ServerLevel level&&level.getEntity(s.rootsTarget) instanceof LivingEntity living?living:null;}
    private static Optional<LivingEntity> lineOfSightTarget(ServerPlayer p,double range){Vec3 start=p.getEyePosition(),end=start.add(p.getLookAngle().scale(range));HitResult block=p.level.clip(new ClipContext(start,end,ClipContext.Block.COLLIDER,ClipContext.Fluid.NONE,p));if(block.getType()!=HitResult.Type.MISS)end=block.getLocation();Vec3 finalEnd=end;AABB box=new AABB(start,end).inflate(1);return p.level.getEntitiesOfClass(LivingEntity.class,box,e->e!=p&&e.isAlive()).stream().filter(e->e.getBoundingBox().inflate(.3).clip(start,finalEnd).isPresent()).min(Comparator.comparingDouble(p::distanceToSqr));}
    public static boolean isRooted(Entity entity){RootState root=ROOTED.get(entity.getUUID());return root!=null&&root.until>entity.level.getGameTime();}
    private static void holdRooted(Entity entity){RootState root=ROOTED.get(entity.getUUID());if(root==null)return;entity.setDeltaMovement(Vec3.ZERO);entity.teleportTo(root.anchor.x,root.anchor.y,root.anchor.z);if(entity instanceof Mob mob)mob.getNavigation().stop();}
    private static void tickRooted(net.minecraft.world.level.Level level,long now){Iterator<Map.Entry<UUID,RootState>> iterator=ROOTED.entrySet().iterator();while(iterator.hasNext()){RootState root=iterator.next().getValue();if(root.until<=now||!root.entity.isAlive()){removeRootVisual(root);iterator.remove();}}for(RootState root:ROOTED.values())if(root.entity.level==level){holdRooted(root.entity);if(root.entity instanceof LivingEntity living)rootsParticles(living);}}
    private static void rootsParticles(LivingEntity victim){if(victim.level instanceof ServerLevel level)level.sendParticles(net.minecraft.core.particles.ParticleTypes.HAPPY_VILLAGER,victim.getX(),victim.getY()+.2,victim.getZ(),5,.5,.15,.5,0);}
    private static ItemStack rangedWeapon(ServerPlayer p,boolean crossbow){ItemStack main=p.getMainHandItem(),off=p.getOffhandItem();if(crossbow){if(main.getItem() instanceof CrossbowItem)return main;if(off.getItem() instanceof CrossbowItem)return off;}else{if(main.getItem() instanceof BowItem||main.getItem() instanceof CrossbowItem)return main;if(off.getItem() instanceof BowItem||off.getItem() instanceof CrossbowItem)return off;}return ItemStack.EMPTY;}
    private static boolean shootAbilityArrow(ServerPlayer p,boolean requireCrossbow,boolean freeExtra){ItemStack weapon=rangedWeapon(p,requireCrossbow);if(weapon.isEmpty())return false;ItemStack ammo=p.getProjectile(weapon);if(ammo.isEmpty()&&!p.getAbilities().instabuild){p.displayClientMessage(Component.literal("No ammunition."),true);return false;}if(ammo.isEmpty())ammo=new ItemStack(Items.ARROW);Arrow arrow=new Arrow(p.level,p);arrow.setPos(p.getX(),p.getEyeY()-.1,p.getZ());arrow.shootFromRotation(p,p.getXRot(),p.getYRot(),0,3.15F,1.0F);arrow.setBaseDamage(2.0);arrow.setCritArrow(true);arrow.getPersistentData().putString("tierborne:ranged_type",weapon.getItem() instanceof CrossbowItem?"crossbow":"bow");if(freeExtra)arrow.pickup=AbstractArrow.Pickup.CREATIVE_ONLY;p.level.addFreshEntity(arrow);if(!freeExtra&&!p.getAbilities().instabuild)ammo.shrink(1);if(!p.getAbilities().instabuild)weapon.hurtAndBreak(1,p,user->user.broadcastBreakEvent(p.getUsedItemHand()));return true;}
    public static double consumeArrowMultiplier(ServerPlayer p,AbstractArrow arrow){State s=state(p);PlayerProgress progress=progress(p);double multiplier=1;String type=arrow.getPersistentData().getString("tierborne:ranged_type");if(type.isEmpty())type=arrow.shotFromCrossbow()?"crossbow":"bow";if(s.fullyChargedDrawing&&"bow".equals(type)){double ratio=Math.min(1,(p.level.getGameTime()-s.fullyChargedStarted)/(double)fullyChargedDrawTicks(progress));double curve=(ratio*ratio+2*ratio)/3.0;multiplier*=1+(RpgBalanceConfig.FULLY_CHARGED_MAX_MULTIPLIER.get()-1)*curve;consumeFullyCharged(p,s,p.level.getGameTime());}if(s.elementalNextArrow){arrow.getPersistentData().putBoolean("tierborne:elemental_shot",true);s.elementalNextArrow=false;}if(progress.hasSkill(ArcherPlayerClass.FIRE))arrow.getPersistentData().putBoolean("tierborne:fire_arrow",true);if(progress.hasSkill(ArcherPlayerClass.ICE))arrow.getPersistentData().putBoolean("tierborne:ice_arrow",true);return multiplier*(1+("crossbow".equals(type)?ArcherStats.crossbowDamage(progress):ArcherStats.bowDamage(progress))/100.0);}
    public static void resetRoot(Entity entity){removeRoot(entity.getUUID());}
    public static boolean fullyChargedActive(ServerPlayer player){return state(player).fullyChargedDrawing;}
    public static void noteFullyChargedDraw(ServerPlayer player){State s=state(player);long now=player.level.getGameTime();if(s.fullyChargedReady&&now<s.fullyChargedReadyUntil){s.fullyChargedReady=false;s.fullyChargedDrawing=true;s.fullyChargedStarted=now;s.fullyChargedWeapon=player.getUseItem();s.bowDelayAccumulator=0;}}
    public static int adjustBowUseDuration(ServerPlayer player,int duration){PlayerProgress progress=progress(player);State s=state(player);double multiplier=ArcherStats.bowDrawTimeMultiplier(progress);if(s.fullyChargedDrawing)multiplier*=RpgBalanceConfig.FULLY_CHARGED_DRAW_TIME_MULTIPLIER.get();if(multiplier<=1)return duration;double cancelledFraction=1-1/multiplier;s.bowDelayAccumulator+=cancelledFraction;if(s.bowDelayAccumulator>=1){s.bowDelayAccumulator-=1;return duration+1;}return duration;}
    private static int fullyChargedDrawTicks(PlayerProgress progress){return Math.max(1,(int)Math.round(20*ArcherStats.bowDrawTimeMultiplier(progress)*RpgBalanceConfig.FULLY_CHARGED_DRAW_TIME_MULTIPLIER.get()));}
    private static void consumeFullyCharged(ServerPlayer player,State s,long now){if(!s.fullyChargedReady&&!s.fullyChargedDrawing)return;s.fullyChargedReady=false;s.fullyChargedDrawing=false;s.fullyChargedWeapon=null;s.fullyChargedCancelAt=0;s.bowDelayAccumulator=0;cooldown(s,"fully_charged",now,RpgBalanceConfig.ticks(RpgBalanceConfig.FULLY_CHARGED_COOLDOWN_SECONDS));}
    private static void cooldown(State s,String id,long now,int duration){s.cooldowns.put(id,now+duration);s.cooldownDurations.put(id,duration);}
    private static String name(String id){if(id.equals("block"))return "Block";AlternateAttackDefinition attack=AlternateAttackDefinition.find(id);return attack==null?id:attack.displayName();}
    private static void preferOtherTargets(ServerPlayer rogue){double radius=RpgBalanceConfig.ROGUE_RETARGET_RADIUS.get();for(Mob mob:rogue.level.getEntitiesOfClass(Mob.class,rogue.getBoundingBox().inflate(radius),m->m.getTarget()==rogue)){ServerPlayer alternative=rogue.getServer().getPlayerList().getPlayers().stream().filter(p->p!=rogue&&p.level==rogue.level&&p.distanceToSqr(mob)<radius*radius).min(Comparator.comparingDouble(mob::distanceToSqr)).orElse(null);if(alternative!=null)mob.setTarget(alternative);}}
    private static void putRoot(Entity entity,long until){removeRoot(entity.getUUID());BlockPos base=null;if(entity.level instanceof ServerLevel level){BlockPos candidate=new BlockPos(net.minecraft.util.Mth.floor(entity.getX()),net.minecraft.util.Mth.floor(entity.getY()),net.minecraft.util.Mth.floor(entity.getZ()));RootVisual visual=new RootVisual(level,candidate);int references=ROOT_VISUALS.getOrDefault(visual,0);if(references>0||level.getBlockState(candidate).isAir()&&level.getBlockState(candidate.above()).isAir()){base=candidate;ROOT_VISUALS.put(visual,references+1);if(references==0){level.setBlock(candidate,net.minecraft.world.level.block.Blocks.TALL_GRASS.defaultBlockState().setValue(net.minecraft.world.level.block.DoublePlantBlock.HALF,net.minecraft.world.level.block.state.properties.DoubleBlockHalf.LOWER),2);level.setBlock(candidate.above(),net.minecraft.world.level.block.Blocks.TALL_GRASS.defaultBlockState().setValue(net.minecraft.world.level.block.DoublePlantBlock.HALF,net.minecraft.world.level.block.state.properties.DoubleBlockHalf.UPPER),2);}}}ROOTED.put(entity.getUUID(),new RootState(entity,entity.position(),until,base));}
    private static void removeRoot(UUID id){RootState root=ROOTED.remove(id);if(root!=null)removeRootVisual(root);}
    private static void removeRootVisual(RootState root){if(root.grassBase==null||!(root.entity.level instanceof ServerLevel level))return;RootVisual visual=new RootVisual(level,root.grassBase);int remaining=ROOT_VISUALS.getOrDefault(visual,1)-1;if(remaining>0){ROOT_VISUALS.put(visual,remaining);return;}ROOT_VISUALS.remove(visual);BlockPos upper=root.grassBase.above();if(level.getBlockState(root.grassBase).is(net.minecraft.world.level.block.Blocks.TALL_GRASS))level.removeBlock(root.grassBase,false);if(level.getBlockState(upper).is(net.minecraft.world.level.block.Blocks.TALL_GRASS))level.removeBlock(upper,false);}
    private record RootVisual(net.minecraft.world.level.Level level,BlockPos base){}
    private record RootState(Entity entity,Vec3 anchor,long until,BlockPos grassBase){}
    public static final class State{private final Map<String,Long> cooldowns=new HashMap<>();private final Map<String,Integer> cooldownDurations=new HashMap<>();private final Map<UUID,Long> lastHit=new HashMap<>();private long utilityReady,normalAttackLockedUntil,drawLockedUntil,nextMultislashHit,multislashStarted,cloakedUntil,leapStarted,heavyMoveUntil,multislashActiveUntil,mainLastAttack=Long.MIN_VALUE,offLastAttack=Long.MIN_VALUE,blockActiveUntil,fireballStarted,fireballRecastUntil,archerMultishotUntil,fullyChargedStarted,fullyChargedReadyUntil,fullyChargedCancelAt,backstepRecastUntil,rootsUntil;private int utilityDuration,normalAttackLockDuration,drawLockDuration,multislashDuration,multislashHitsRemaining,multislashAnimationIndex,lastSelectedSlot=-1,blockDuration,fireballDuration,fireballShots;private double bowDelayAccumulator,fireballSequenceCharge;private boolean blocking,blockExhausted,leaping,wasHoldingSword,multislashUsesOffhand,multislashPendingCooldown,fireballActive,fireballCharging,alternateHeld,fullyChargedReady,fullyChargedDrawing,elementalNextArrow,rootsActive;private UUID rootsTarget;private ItemStack fullyChargedWeapon;private net.minecraft.world.item.Item lastMainItem;public boolean blocking(){return blocking;}public long parryReady;}
}
