package com.ollie.tierborne.playerclass;

import com.ollie.tierborne.Tierborne;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.Items;

import java.util.List;
import java.util.Set;

/** Data-driven Archer tree. Everything before a subclass remains available to every Archer. */
public final class ArcherPlayerClass extends PlayerClass {
    public static final String ID="archer", ROOT="archer_root";
    public static final String CROSSBOW_DAMAGE_1="archer_crossbow_damage_1", CROSSBOW_SPEED_1="archer_crossbow_speed_1", MULTISHOT="archer_multishot", CROSSBOWMAN="archer_subclass_crossbowman", CROSSBOW_DAMAGE_2="crossbowman_damage", CROSSBOW_SPEED_2="crossbowman_speed";
    public static final String BOW_DAMAGE_1="archer_bow_damage_1", BOW_HANDLING="archer_bow_handling", FULLY_CHARGED="archer_fully_charged", LONGBOWMAN="archer_subclass_longbowman", LONGBOW_DAMAGE="longbowman_damage", FULLY_CHARGED_MOBILITY="longbowman_fully_charged_mobility";
    public static final String ELEMENTAL_DAMAGE_1="archer_elemental_damage_1", ELEMENTAL_DAMAGE_2="archer_elemental_damage_2", ELEMENTAL_SHOT="archer_elemental_shot", ELEMENTAL_ARCHER="archer_subclass_elemental", FIRE="elemental_archer_fire", FIRE_DURATION="elemental_archer_fire_duration", FIRE_DAMAGE="elemental_archer_fire_damage", ICE="elemental_archer_ice", ICE_POTENCY="elemental_archer_ice_potency", ICE_DURATION="elemental_archer_ice_duration";
    public static final String RANGER_DAMAGE="archer_ranger_damage", RANGER_MOVEMENT="archer_ranger_movement", BACKSTEP="archer_backstep", RANGER="archer_subclass_ranger", BACKSTEP_DOUBLE="ranger_backstep_double", BACKSTEP_DIRECTIONAL="ranger_backstep_directional", BACKSTEP_RANGE="ranger_backstep_range", NATURES_ROOTS="ranger_natures_roots";
    private static final List<String> SUBCLASSES=List.of(CROSSBOWMAN,LONGBOWMAN,ELEMENTAL_ARCHER,RANGER);
    private static final List<Skill> SKILLS=List.of(
        skill(ROOT,"Archer","Bow and crossbow mastery with a reusable mobility Dash.",0,Items.BOW,0,0,List.of(),List.of(),true,null,SkillEffect.NONE),
        upgrade(CROSSBOW_DAMAGE_1,"Crossbow Damage I",SkillBonusType.CROSSBOW_DAMAGE,15,Items.CROSSBOW,-2,-2,ROOT), node(CROSSBOW_SPEED_1,"Crossbow Charge Speed I","Loads crossbows faster.",Items.CLOCK,-3,-3,CROSSBOW_DAMAGE_1), alt(MULTISHOT,"Multishot","Fire a charged crossbow twice, with a short active delay.",Items.FIREWORK_ROCKET,-4,-4,CROSSBOW_SPEED_1), subclass(CROSSBOWMAN,"Crossbowman",Items.CROSSBOW,-5,-5,MULTISHOT), node(CROSSBOW_DAMAGE_2,"Crossbow Damage II","Further increases Crossbowman damage.",Items.ARROW,-6,-5,CROSSBOWMAN), node(CROSSBOW_SPEED_2,"Crossbow Charge Speed II","Further improves crossbow loading speed.",Items.CLOCK,-5,-6,CROSSBOWMAN),
        upgrade(BOW_DAMAGE_1,"Bow Damage I",SkillBonusType.BOW_DAMAGE,15,Items.BOW,2,-2,ROOT), node(BOW_HANDLING,"Bow Handling","Improves normal bow charge speed.",Items.FEATHER,3,-3,BOW_DAMAGE_1), alt(FULLY_CHARGED,"Fully Charged","Empower one slowly charged bow shot for up to four times damage.",Items.SPECTRAL_ARROW,4,-4,BOW_HANDLING), subclass(LONGBOWMAN,"Longbowman",Items.BOW,5,-5,FULLY_CHARGED), node(LONGBOW_DAMAGE,"Increased Bow Damage","Further increases Longbowman bow damage.",Items.ARROW,6,-5,LONGBOWMAN), node(FULLY_CHARGED_MOBILITY,"Improved Fully Charged Mobility","Reduces the empowered-shot movement penalty.",Items.LEATHER_BOOTS,5,-6,LONGBOWMAN),
        upgrade(ELEMENTAL_DAMAGE_1,"Ranged Damage I",SkillBonusType.RANGED_DAMAGE,10,Items.ARROW,2,2,ROOT), upgrade(ELEMENTAL_DAMAGE_2,"Ranged Damage II",SkillBonusType.RANGED_DAMAGE,10,Items.SPECTRAL_ARROW,3,3,ELEMENTAL_DAMAGE_1), alt(ELEMENTAL_SHOT,"Elemental Shot","Instantly fire a full-power shot that burns and heavily slows.",Items.TIPPED_ARROW,4,4,ELEMENTAL_DAMAGE_2), subclass(ELEMENTAL_ARCHER,"Elemental Archer",Items.BLAZE_POWDER,5,5,ELEMENTAL_SHOT), specialization(FIRE,"Fire",Items.FIRE_CHARGE,6,4,ELEMENTAL_ARCHER,ICE), node(FIRE_DURATION,"Burn Duration","Extends the Fire arrow passive.",Items.BLAZE_POWDER,7,3,FIRE), node(FIRE_DAMAGE,"Fire Damage","Adds elemental fire damage to Fire arrows.",Items.MAGMA_CREAM,7,5,FIRE), specialization(ICE,"Ice",Items.SNOWBALL,6,6,ELEMENTAL_ARCHER,FIRE), node(ICE_POTENCY,"Ice Potency","Raises the Ice arrow Slowness level.",Items.PACKED_ICE,7,6,ICE), node(ICE_DURATION,"Ice Duration","Extends the Ice arrow Slowness duration.",Items.CLOCK,7,7,ICE),
        upgrade(RANGER_DAMAGE,"Ranged Precision",SkillBonusType.RANGED_DAMAGE,10,Items.ARROW,-2,2,ROOT), upgrade(RANGER_MOVEMENT,"Ranger Agility",SkillBonusType.MOVEMENT_SPEED,10,Items.LEATHER_BOOTS,-3,3,RANGER_DAMAGE), alt(BACKSTEP,"Backstep","Fire a full-power arrow while dashing away.",Items.FEATHER,-4,4,RANGER_MOVEMENT), subclass(RANGER,"Ranger",Items.LEATHER_BOOTS,-5,5,BACKSTEP), node(BACKSTEP_DOUBLE,"Double Backstep","Adds a one-second recast window before cooldown.",Items.RABBIT_FOOT,-6,4,RANGER), node(BACKSTEP_DIRECTIONAL,"Directional Backstep","Uses current movement input to choose dash direction.",Items.COMPASS,-6,5,RANGER), node(BACKSTEP_RANGE,"Backstep Range","Increases Backstep distance.",Items.FEATHER,-6,6,RANGER), alt(NATURES_ROOTS,"Nature's Roots","Channel to root and silence a crosshair target.",Items.VINE,-7,7,List.of(BACKSTEP_DOUBLE,BACKSTEP_DIRECTIONAL,BACKSTEP_RANGE))
    );
    public ArcherPlayerClass(){super(ID,"Archer","A mobile ranged fighter mastering bows, crossbows, elements and nature.",texture("archer"),Items.BOW,List.of("Crossbowman","Longbowman","Elemental Archer","Ranger"));}
    @Override public List<Skill> skills(){return SKILLS;}
    public Skill selectedSubclass(Set<String> skills){return SKILLS.stream().filter(s->s.effect()==SkillEffect.CLASS_SUBCLASS&&SUBCLASSES.contains(s.id())&&skills.contains(s.id())).findFirst().orElse(null);}
    private static Skill subclass(String id,String name,Item icon,int x,int y,String pre){return skill(id,name,"Choose the "+name+" subclass. Excludes the other Archer subclasses.",1,icon,x,y,List.of(pre),SUBCLASSES.stream().filter(s->!s.equals(id)).toList(),false,null,SkillEffect.CLASS_SUBCLASS);}
    private static Skill specialization(String id,String name,Item icon,int x,int y,String pre,String exclusion){return skill(id,name,"Choose the "+name+" elemental specialisation.",0,icon,x,y,List.of(pre),List.of(exclusion),false,null,SkillEffect.NONE);}
    private static Skill alt(String id,String name,String desc,Item icon,int x,int y,String pre){return alt(id,name,desc,icon,x,y,List.of(pre));}
    private static Skill alt(String id,String name,String desc,Item icon,int x,int y,List<String> pre){return skill(id,name,"Alternate Attack: "+desc,1,icon,x,y,pre,List.of(),false,null,SkillEffect.ALTERNATE_ATTACK);}
    private static Skill node(String id,String name,String desc,Item icon,int x,int y,String pre){return skill(id,name,desc,1,icon,x,y,List.of(pre),List.of(),false,null,SkillEffect.NONE);}
    private static Skill upgrade(String id,String name,SkillBonusType type,int amount,Item icon,int x,int y,String pre){return skill(id,name,"Adds "+amount+"% "+type.displayName()+".",1,icon,x,y,List.of(pre),List.of(),false,new SkillUpgrade(type,amount),SkillEffect.NONE);}
    private static Skill skill(String id,String name,String desc,int cost,Item item,int x,int y,List<String> pre,List<String> exclusions,boolean automatic,SkillUpgrade upgrade,SkillEffect effect){return new Skill(id,name,name.substring(0,1),desc,cost,texture(id),SkillIcon.item(item),x,y,pre,exclusions,automatic,upgrade,effect);}
    private static ResourceLocation texture(String name){return new ResourceLocation(Tierborne.MOD_ID,"textures/gui/icons/archer_"+name+".png");}
}
