package com.ollie.tierborne.config;

import net.minecraftforge.common.ForgeConfigSpec;

public final class RpgBalanceConfig {
    public static final ForgeConfigSpec SPEC;

    public static final ForgeConfigSpec.DoubleValue SWORDMASTER_DAMAGE;
    public static final ForgeConfigSpec.DoubleValue SWORDMASTER_SPEED;
    public static final ForgeConfigSpec.DoubleValue DASH_VELOCITY;
    public static final ForgeConfigSpec.DoubleValue DASH_COOLDOWN_SECONDS;
    public static final ForgeConfigSpec.DoubleValue DASH_UPGRADE_VELOCITY;
    public static final ForgeConfigSpec.DoubleValue DASH_UPGRADE_COOLDOWN_SECONDS;
    public static final ForgeConfigSpec.DoubleValue DASH_STRIKE_DISTANCE;
    public static final ForgeConfigSpec.DoubleValue DASH_STRIKE_DAMAGE;
    public static final ForgeConfigSpec.DoubleValue DASH_STRIKE_COOLDOWN_SECONDS;
    public static final ForgeConfigSpec.DoubleValue DASH_STRIKE_UPGRADE_DAMAGE;
    public static final ForgeConfigSpec.DoubleValue SWORDMASTER_UPGRADE_DAMAGE;
    public static final ForgeConfigSpec.DoubleValue SWORDMASTER_UPGRADE_SPEED;

    public static final ForgeConfigSpec.DoubleValue DUAL_DAMAGE;
    public static final ForgeConfigSpec.DoubleValue DUAL_ATTACK_SPEED;
    public static final ForgeConfigSpec.DoubleValue DUAL_DAMAGE_UPGRADE;
    public static final ForgeConfigSpec.DoubleValue DUAL_SPEED_UPGRADE;
    public static final ForgeConfigSpec.DoubleValue BLOCK_PERCENT;
    public static final ForgeConfigSpec.DoubleValue SHIELD_BLOCK_PERCENT;
    public static final ForgeConfigSpec.DoubleValue PARRY_COOLDOWN_SECONDS;
    public static final ForgeConfigSpec.DoubleValue MULTISLASH_DURATION_SECONDS;
    public static final ForgeConfigSpec.DoubleValue MULTISLASH_COOLDOWN_SECONDS;
    public static final ForgeConfigSpec.DoubleValue BLOCK_MAX_DURATION_SECONDS;
    public static final ForgeConfigSpec.DoubleValue BLOCK_COOLDOWN_SECONDS;
    public static final ForgeConfigSpec.DoubleValue DASH_STRIKE_UPGRADED_DISTANCE;
    public static final ForgeConfigSpec.DoubleValue DASH_STRIKE_UPGRADED_COOLDOWN_SECONDS;
    public static final ForgeConfigSpec.DoubleValue FIREBALL_DAMAGE_PERCENT;
    public static final ForgeConfigSpec.DoubleValue FIREBALL_KNOCKBACK;
    public static final ForgeConfigSpec.DoubleValue FIREBALL_IGNITION_SECONDS;
    public static final ForgeConfigSpec.DoubleValue FIREBALL_CAST_SECONDS;
    public static final ForgeConfigSpec.DoubleValue FIREBALL_COOLDOWN_SECONDS;
    public static final ForgeConfigSpec.DoubleValue FIREBALL_UPGRADED_COOLDOWN_SECONDS;
    public static final ForgeConfigSpec.DoubleValue MAGIC_SWORD_FIRE_SECONDS;
    public static final ForgeConfigSpec.DoubleValue ELEMENTAL_VULNERABILITY_SECONDS;
    public static final ForgeConfigSpec.DoubleValue ELEMENTAL_VULNERABILITY_BONUS_PERCENT;
    public static final ForgeConfigSpec.DoubleValue FIREBALL_MAX_CHARGE_SECONDS;
    public static final ForgeConfigSpec.DoubleValue FIREBALL_MIN_CHARGE_PERCENT;
    public static final ForgeConfigSpec.DoubleValue FIREBALL_MIN_DAMAGE_PERCENT;
    public static final ForgeConfigSpec.DoubleValue FIREBALL_MAX_DAMAGE_PERCENT;
    public static final ForgeConfigSpec.DoubleValue HOMING_FIREBALL_MAX_CONTROL_SECONDS;
    public static final ForgeConfigSpec.DoubleValue HOMING_FIREBALL_STEERING_STRENGTH;
    public static final ForgeConfigSpec.DoubleValue HOMING_FIREBALL_PUSH_STRENGTH;
    public static final ForgeConfigSpec.DoubleValue HOMING_FIREBALL_PULL_STRENGTH;
    public static final ForgeConfigSpec.DoubleValue FIREBALL_BASE_SPEED;
    public static final ForgeConfigSpec.DoubleValue FIREBALL_SPEED_I;
    public static final ForgeConfigSpec.DoubleValue FIREBALL_SPEED_II;
    public static final ForgeConfigSpec.DoubleValue FIREBALL_DAMAGE_I;
    public static final ForgeConfigSpec.DoubleValue FIREBALL_DAMAGE_II;
    public static final ForgeConfigSpec.IntValue FIREBALL_MIN_CORE_PARTICLES;
    public static final ForgeConfigSpec.IntValue FIREBALL_MAX_CORE_PARTICLES;
    public static final ForgeConfigSpec.IntValue FIREBALL_MIN_TRAIL_PARTICLES;
    public static final ForgeConfigSpec.IntValue FIREBALL_MAX_TRAIL_PARTICLES;
    public static final ForgeConfigSpec.DoubleValue FIREBALL_MIN_PARTICLE_RADIUS;
    public static final ForgeConfigSpec.DoubleValue FIREBALL_MAX_PARTICLE_RADIUS;
    public static final ForgeConfigSpec.IntValue HOMING_FIREBALL_BASE_MAX_COUNT;
    public static final ForgeConfigSpec.IntValue HOMING_FIREBALL_ADDITIONAL_COUNT;
    public static final ForgeConfigSpec.DoubleValue HOMING_FOLLOWER_STEERING_STRENGTH;
    public static final ForgeConfigSpec.DoubleValue HOMING_FOLLOWER_CATCHUP_MULTIPLIER;
    public static final ForgeConfigSpec.DoubleValue HOMING_FOLLOWER_DISTANCE;
    public static final ForgeConfigSpec.DoubleValue HOMING_FIREBALL_SPEED_MULTIPLIER;

    public static final ForgeConfigSpec.DoubleValue HEAVY_DAMAGE;
    public static final ForgeConfigSpec.DoubleValue HEAVY_ATTACK_SPEED;
    public static final ForgeConfigSpec.DoubleValue HEAVY_MOVE_PENALTY;
    public static final ForgeConfigSpec.DoubleValue HEAVY_MOVE_LINGER_SECONDS;
    public static final ForgeConfigSpec.DoubleValue HEAVY_DRAW_DELAY_SECONDS;
    public static final ForgeConfigSpec.DoubleValue HEAVY_ATTACK_DAMAGE;
    public static final ForgeConfigSpec.DoubleValue HEAVY_ATTACK_UPGRADE_DAMAGE;
    public static final ForgeConfigSpec.DoubleValue HEAVY_ATTACK_COOLDOWN_SECONDS;
    public static final ForgeConfigSpec.DoubleValue HEAVY_ATTACK_UPGRADE_COOLDOWN_SECONDS;
    public static final ForgeConfigSpec.DoubleValue HEAVY_RANGE;
    public static final ForgeConfigSpec.DoubleValue HEAVY_UPGRADE_DAMAGE;
    public static final ForgeConfigSpec.DoubleValue LEAP_LAUNCH;
    public static final ForgeConfigSpec.DoubleValue LEAP_RADIUS;
    public static final ForgeConfigSpec.DoubleValue LEAP_KNOCKBACK;
    public static final ForgeConfigSpec.DoubleValue LEAP_COOLDOWN_SECONDS;

    public static final ForgeConfigSpec.DoubleValue ROGUE_HEALTH_PENALTY;
    public static final ForgeConfigSpec.DoubleValue ROGUE_SPEED;
    public static final ForgeConfigSpec.DoubleValue CLOAK_DURATION_SECONDS;
    public static final ForgeConfigSpec.DoubleValue CLOAK_COOLDOWN_SECONDS;
    public static final ForgeConfigSpec.DoubleValue BACKSTAB_DAMAGE;
    public static final ForgeConfigSpec.DoubleValue BACKSTAB_DOT_THRESHOLD;
    public static final ForgeConfigSpec.DoubleValue FIRST_HIT_DAMAGE;
    public static final ForgeConfigSpec.DoubleValue FIRST_HIT_RESET_SECONDS;
    public static final ForgeConfigSpec.DoubleValue NON_AGGRO_DAMAGE;
    public static final ForgeConfigSpec.DoubleValue ROGUE_RETARGET_RADIUS;
    public static final ForgeConfigSpec.DoubleValue ARCHER_BOW_DAMAGE, ARCHER_CROSSBOW_DAMAGE, ARCHER_DASH_VELOCITY, ARCHER_DASH_DISTANCE, ARCHER_DASH_COOLDOWN_SECONDS;
    public static final ForgeConfigSpec.DoubleValue CROSSBOW_DAMAGE_I, CROSSBOW_CHARGE_SPEED_I, MULTISHOT_DELAY_SECONDS, MULTISHOT_COOLDOWN_SECONDS, CROSSBOWMAN_DAMAGE, CROSSBOW_DAMAGE_II, CROSSBOW_CHARGE_SPEED_II;
    public static final ForgeConfigSpec.DoubleValue BOW_DAMAGE_I, BOW_HANDLING_SPEED, FULLY_CHARGED_MAX_MULTIPLIER, FULLY_CHARGED_DRAW_TIME_MULTIPLIER, FULLY_CHARGED_READY_WINDOW_SECONDS, FULLY_CHARGED_MOVEMENT_PENALTY, FULLY_CHARGED_IMPROVED_MOVEMENT_PENALTY, FULLY_CHARGED_COOLDOWN_SECONDS, LONGBOWMAN_DAMAGE, LONGBOWMAN_CHARGE_SPEED, LONGBOWMAN_DRAW_MOVEMENT, LONGBOW_DAMAGE_UPGRADE;
    public static final ForgeConfigSpec.DoubleValue ELEMENTAL_RANGED_DAMAGE_I, ELEMENTAL_RANGED_DAMAGE_II, ELEMENTAL_SHOT_COOLDOWN_SECONDS, ELEMENTAL_SHOT_FIRE_SECONDS, ELEMENTAL_SHOT_SLOW_SECONDS, FIRE_PASSIVE_SECONDS, FIRE_UPGRADED_SECONDS, FIRE_BONUS_DAMAGE, ICE_PASSIVE_SECONDS, ICE_UPGRADED_SECONDS;
    public static final ForgeConfigSpec.IntValue ELEMENTAL_SHOT_SLOW_LEVEL, ICE_PASSIVE_LEVEL, ICE_UPGRADED_LEVEL;
    public static final ForgeConfigSpec.DoubleValue RANGER_RANGED_DAMAGE, RANGER_PRE_MOVEMENT, RANGER_MOVEMENT, BACKSTEP_DISTANCE, BACKSTEP_UPGRADED_DISTANCE, BACKSTEP_COOLDOWN_SECONDS, BACKSTEP_RECAST_SECONDS, ROOTS_RANGE, ROOTS_CHANNEL_SECONDS, ROOTS_TAIL_SECONDS, ROOTS_COOLDOWN_SECONDS;

    static {
        ForgeConfigSpec.Builder b = new ForgeConfigSpec.Builder();
        b.push("swordmaster");
        SWORDMASTER_DAMAGE = percent(b, "subclassSwordDamagePercent", 20.0);
        SWORDMASTER_SPEED = percent(b, "subclassMovementSpeedPercent", 10.0);
        DASH_VELOCITY = value(b, "dashVelocity", 1.35, 0.0, 5.0);
        DASH_COOLDOWN_SECONDS = seconds(b, "dashCooldownSeconds", 4.0);
        DASH_UPGRADE_VELOCITY = value(b, "upgradedDashVelocity", 1.75, 0.0, 5.0);
        DASH_UPGRADE_COOLDOWN_SECONDS = seconds(b, "upgradedDashCooldownSeconds", 2.5);
        DASH_STRIKE_DISTANCE = value(b, "dashStrikeDistanceBlocks", 5.0, 1.0, 16.0);
        DASH_STRIKE_DAMAGE = percent(b, "dashStrikeExtraDamagePercent", 30.0);
        DASH_STRIKE_COOLDOWN_SECONDS = seconds(b, "dashStrikeCooldownSeconds", 5.0);
        DASH_STRIKE_UPGRADE_DAMAGE = percent(b, "upgradedDashStrikeExtraDamagePercent", 55.0);
        DASH_STRIKE_UPGRADED_DISTANCE = value(b, "upgradedDashStrikeDistanceBlocks", 7.0, 1.0, 24.0);
        DASH_STRIKE_UPGRADED_COOLDOWN_SECONDS = seconds(b, "upgradedDashStrikeCooldownSeconds", 4.0);
        SWORDMASTER_UPGRADE_DAMAGE = percent(b, "swordDamageUpgradePercent", 20.0);
        SWORDMASTER_UPGRADE_SPEED = percent(b, "movementSpeedUpgradePercent", 10.0);
        b.pop().push("dualSwordsman");
        DUAL_DAMAGE = percent(b, "damagePerSwordPercent", -30.0);
        DUAL_ATTACK_SPEED = percent(b, "attackSpeedPercent", 0.0);
        DUAL_DAMAGE_UPGRADE = percent(b, "upgradedDamagePerSwordPercent", -15.0);
        DUAL_SPEED_UPGRADE = percent(b, "upgradedAttackSpeedPercent", 25.0);
        BLOCK_PERCENT = percent(b, "dualSwordsmanBaseBlockPercent", 100.0);
        SHIELD_BLOCK_PERCENT = percent(b, "shieldBlockPercent", 40.0);
        PARRY_COOLDOWN_SECONDS = seconds(b, "parryCooldownSeconds", 3.0);
        MULTISLASH_DURATION_SECONDS = seconds(b, "multislashDurationSeconds", 1.0);
        MULTISLASH_COOLDOWN_SECONDS = seconds(b, "multislashCooldownSeconds", 6.0);
        BLOCK_MAX_DURATION_SECONDS = seconds(b, "dualSwordsmanMaxBlockDurationSeconds", 5.0);
        BLOCK_COOLDOWN_SECONDS = seconds(b, "dualSwordsmanBlockCooldownSeconds", 5.0);
        b.pop().push("magicSwordsman");
        FIREBALL_DAMAGE_PERCENT = percent(b, "fireballSwordDamagePercent", 100.0);
        FIREBALL_KNOCKBACK = value(b, "fireballKnockbackStrength", 1.0, 0.0, 5.0);
        FIREBALL_IGNITION_SECONDS = seconds(b, "fireballIgnitionSeconds", 4.0);
        FIREBALL_CAST_SECONDS = seconds(b, "fireballCastTimeSeconds", 1.5);
        FIREBALL_COOLDOWN_SECONDS = seconds(b, "fireballCooldownSeconds", 6.0);
        FIREBALL_UPGRADED_COOLDOWN_SECONDS = seconds(b, "upgradedFireballCooldownSeconds", 4.0);
        MAGIC_SWORD_FIRE_SECONDS = seconds(b, "intrinsicSwordFireSeconds", 4.0);
        ELEMENTAL_VULNERABILITY_SECONDS = seconds(b, "elementalVulnerabilityDurationSeconds", 6.0);
        ELEMENTAL_VULNERABILITY_BONUS_PERCENT = percent(b, "elementalVulnerabilityDamageBonusPercent", 25.0);
        FIREBALL_MAX_CHARGE_SECONDS = seconds(b, "fireballMaximumChargeSeconds", 1.5);
        FIREBALL_MIN_CHARGE_PERCENT = percent(b, "fireballMinimumUsableChargePercent", 10.0);
        FIREBALL_MIN_DAMAGE_PERCENT = percent(b, "fireballMinimumDamageMultiplierPercent", 30.0);
        FIREBALL_MAX_DAMAGE_PERCENT = percent(b, "fireballMaximumDamageMultiplierPercent", 100.0);
        HOMING_FIREBALL_MAX_CONTROL_SECONDS = seconds(b, "homingFireballMaxControlSeconds", 10.0);
        HOMING_FIREBALL_STEERING_STRENGTH = value(b, "homingFireballSteeringStrength", 0.12, 0.0, 1.0);
        HOMING_FIREBALL_PUSH_STRENGTH = value(b, "homingFireballPushStrength", 0.35, 0.0, 3.0);
        HOMING_FIREBALL_PULL_STRENGTH = value(b, "homingFireballPullStrength", 0.35, 0.0, 3.0);
        FIREBALL_BASE_SPEED = value(b, "fireballSpeedBlocksPerSecond", 23.0, 1.0, 80.0);
        FIREBALL_SPEED_I = value(b, "fireballSpeedAfterUpgradeI", 27.0, 1.0, 80.0);
        FIREBALL_SPEED_II = value(b, "fireballSpeedAfterUpgradeII", 31.0, 1.0, 80.0);
        FIREBALL_DAMAGE_I = percent(b, "fireballDamageAfterUpgradeIPercent", 125.0);
        FIREBALL_DAMAGE_II = percent(b, "fireballDamageAfterUpgradeIIPercent", 150.0);
        FIREBALL_MIN_CORE_PARTICLES = b.defineInRange("fireballMinimumCoreParticles", 4, 0, 64);
        FIREBALL_MAX_CORE_PARTICLES = b.defineInRange("fireballMaximumCoreParticles", 18, 0, 96);
        FIREBALL_MIN_TRAIL_PARTICLES = b.defineInRange("fireballMinimumTrailParticles", 1, 0, 32);
        FIREBALL_MAX_TRAIL_PARTICLES = b.defineInRange("fireballMaximumTrailParticles", 6, 0, 48);
        FIREBALL_MIN_PARTICLE_RADIUS = value(b, "fireballMinimumParticleRadius", 0.06, 0.0, 1.0);
        FIREBALL_MAX_PARTICLE_RADIUS = value(b, "fireballMaximumParticleRadius", 0.28, 0.0, 1.5);
        HOMING_FIREBALL_BASE_MAX_COUNT = b.defineInRange("maxHomingFireballs", 2, 1, 16);
        HOMING_FIREBALL_ADDITIONAL_COUNT = b.defineInRange("additionalFireballUpgradeCount", 1, 0, 16);
        HOMING_FOLLOWER_STEERING_STRENGTH = value(b, "homingFollowerSteeringStrength", 0.16, 0.0, 1.0);
        HOMING_FOLLOWER_CATCHUP_MULTIPLIER = value(b, "homingFollowerCatchupMultiplier", 1.25, 1.0, 4.0);
        HOMING_FOLLOWER_DISTANCE = value(b, "homingFollowerDistanceBlocks", 1.5, 0.25, 12.0);
        HOMING_FIREBALL_SPEED_MULTIPLIER = value(b, "homingFireballSpeedMultiplier", 0.5, 0.05, 1.0);
        b.pop().push("heavySwordsman");
        HEAVY_DAMAGE = percent(b, "subclassSwordDamagePercent", 75.0);
        HEAVY_ATTACK_SPEED = percent(b, "attackSpeedPercent", -40.0);
        HEAVY_MOVE_PENALTY = percent(b, "swordMovementSpeedPercent", -25.0);
        HEAVY_MOVE_LINGER_SECONDS = seconds(b, "movementPenaltyLingerSeconds", 1.0);
        HEAVY_DRAW_DELAY_SECONDS = seconds(b, "swordDrawDelaySeconds", 1.0);
        HEAVY_ATTACK_DAMAGE = percent(b, "heavyAttackExtraDamagePercent", 30.0);
        HEAVY_ATTACK_UPGRADE_DAMAGE = percent(b, "upgradedHeavyAttackExtraDamagePercent", 65.0);
        HEAVY_ATTACK_COOLDOWN_SECONDS = seconds(b, "heavyAttackCooldownSeconds", 2.0);
        HEAVY_ATTACK_UPGRADE_COOLDOWN_SECONDS = seconds(b, "upgradedHeavyAttackCooldownSeconds", 1.25);
        HEAVY_RANGE = value(b, "meleeRangeBonusBlocks", 1.5, 0.0, 8.0);
        HEAVY_UPGRADE_DAMAGE = percent(b, "swordDamageUpgradePercent", 35.0);
        LEAP_LAUNCH = value(b, "leapLaunchVelocity", 0.85, 0.1, 3.0);
        LEAP_RADIUS = value(b, "leapImpactRadiusBlocks", 2.0, 0.5, 12.0);
        LEAP_KNOCKBACK = value(b, "leapKnockbackStrength", 1.6, 0.0, 8.0);
        LEAP_COOLDOWN_SECONDS = seconds(b, "leapCooldownSeconds", 8.0);
        b.pop().push("rogue");
        ROGUE_HEALTH_PENALTY = value(b, "maxHealthPenalty", 4.0, 0.0, 19.0);
        ROGUE_SPEED = percent(b, "movementSpeedPercent", 20.0);
        CLOAK_DURATION_SECONDS = seconds(b, "cloakDurationSeconds", 5.0);
        CLOAK_COOLDOWN_SECONDS = seconds(b, "cloakCooldownSeconds", 12.0);
        BACKSTAB_DAMAGE = percent(b, "backstabExtraDamagePercent", 50.0);
        BACKSTAB_DOT_THRESHOLD = value(b, "backstabFacingDotThreshold", 0.5, -1.0, 1.0);
        FIRST_HIT_DAMAGE = percent(b, "firstHitExtraDamagePercent", 35.0);
        FIRST_HIT_RESET_SECONDS = seconds(b, "firstHitResetSeconds", 10.0);
        NON_AGGRO_DAMAGE = percent(b, "nonAggroExtraDamagePercent", 25.0);
        ROGUE_RETARGET_RADIUS = value(b, "alternativePlayerTargetRadiusBlocks", 16.0, 1.0, 64.0);
        b.pop().push("archer");
        ARCHER_BOW_DAMAGE=percent(b,"rootBowDamagePercent",15); ARCHER_CROSSBOW_DAMAGE=percent(b,"rootCrossbowDamagePercent",15); ARCHER_DASH_VELOCITY=value(b,"dashVelocity",1.35,0,5); ARCHER_DASH_DISTANCE=value(b,"dashDistanceBlocks",5,0,20); ARCHER_DASH_COOLDOWN_SECONDS=seconds(b,"dashCooldownSeconds",4);
        b.pop().push("crossbowman");
        CROSSBOW_DAMAGE_I=percent(b,"preSubclassDamagePercent",15); CROSSBOW_CHARGE_SPEED_I=percent(b,"preSubclassChargeSpeedPercent",20); MULTISHOT_DELAY_SECONDS=seconds(b,"multishotSecondShotDelaySeconds",0.5); MULTISHOT_COOLDOWN_SECONDS=seconds(b,"multishotCooldownSeconds",7); CROSSBOWMAN_DAMAGE=percent(b,"subclassDamagePercent",35); CROSSBOW_DAMAGE_II=percent(b,"exclusiveDamagePercent",25); CROSSBOW_CHARGE_SPEED_II=percent(b,"exclusiveChargeSpeedPercent",25);
        b.pop().push("longbowman");
        BOW_DAMAGE_I=percent(b,"preSubclassDamagePercent",15); BOW_HANDLING_SPEED=percent(b,"preSubclassChargeSpeedPercent",10); FULLY_CHARGED_MAX_MULTIPLIER=value(b,"fullyChargedMaximumDamageMultiplier",4,1,20); FULLY_CHARGED_DRAW_TIME_MULTIPLIER=value(b,"fullyChargedDrawTimeMultiplier",2,1,10); FULLY_CHARGED_READY_WINDOW_SECONDS=seconds(b,"fullyChargedReadyWindowSeconds",3); FULLY_CHARGED_MOVEMENT_PENALTY=percent(b,"fullyChargedMovementPercent",-50); FULLY_CHARGED_IMPROVED_MOVEMENT_PENALTY=percent(b,"improvedFullyChargedMovementPercent",-25); FULLY_CHARGED_COOLDOWN_SECONDS=seconds(b,"fullyChargedCooldownSeconds",10); LONGBOWMAN_DAMAGE=percent(b,"subclassBowDamagePercent",75); LONGBOWMAN_CHARGE_SPEED=percent(b,"normalBowChargeSpeedPercent",-50); LONGBOWMAN_DRAW_MOVEMENT=percent(b,"movementWhileDrawingPercent",-50); LONGBOW_DAMAGE_UPGRADE=percent(b,"exclusiveBowDamagePercent",35);
        b.pop().push("elementalArcher");
        ELEMENTAL_RANGED_DAMAGE_I=percent(b,"preSubclassRangedDamageIPercent",10); ELEMENTAL_RANGED_DAMAGE_II=percent(b,"preSubclassRangedDamageIIPercent",10); ELEMENTAL_SHOT_COOLDOWN_SECONDS=seconds(b,"elementalShotCooldownSeconds",10); ELEMENTAL_SHOT_FIRE_SECONDS=seconds(b,"elementalShotFireSeconds",5); ELEMENTAL_SHOT_SLOW_LEVEL=b.defineInRange("elementalShotSlownessLevel",5,1,10); ELEMENTAL_SHOT_SLOW_SECONDS=seconds(b,"elementalShotSlownessSeconds",2); FIRE_PASSIVE_SECONDS=seconds(b,"fireArrowBurnSeconds",5); FIRE_UPGRADED_SECONDS=seconds(b,"upgradedFireArrowBurnSeconds",8); FIRE_BONUS_DAMAGE=percent(b,"fireArrowBonusDamagePercent",20); ICE_PASSIVE_LEVEL=b.defineInRange("iceArrowSlownessLevel",3,1,10); ICE_UPGRADED_LEVEL=b.defineInRange("upgradedIceArrowSlownessLevel",5,1,10); ICE_PASSIVE_SECONDS=seconds(b,"iceArrowSlownessSeconds",0.5); ICE_UPGRADED_SECONDS=seconds(b,"upgradedIceArrowSlownessSeconds",1.5);
        b.pop().push("ranger");
        RANGER_RANGED_DAMAGE=percent(b,"preSubclassRangedDamagePercent",10); RANGER_PRE_MOVEMENT=percent(b,"preSubclassMovementSpeedPercent",10); RANGER_MOVEMENT=percent(b,"subclassMovementSpeedPercent",20); BACKSTEP_DISTANCE=value(b,"backstepDistanceBlocks",5,0,20); BACKSTEP_UPGRADED_DISTANCE=value(b,"upgradedBackstepDistanceBlocks",7,0,30); BACKSTEP_COOLDOWN_SECONDS=seconds(b,"backstepCooldownSeconds",6); BACKSTEP_RECAST_SECONDS=seconds(b,"backstepRecastWindowSeconds",1); ROOTS_RANGE=value(b,"naturesRootsRangeBlocks",16,1,64); ROOTS_CHANNEL_SECONDS=seconds(b,"naturesRootsMaximumChannelSeconds",5); ROOTS_TAIL_SECONDS=seconds(b,"naturesRootsTargetTailSeconds",0.5); ROOTS_COOLDOWN_SECONDS=seconds(b,"naturesRootsCooldownSeconds",15);
        b.pop();
        SPEC = b.build();
    }

    private RpgBalanceConfig() {}
    private static ForgeConfigSpec.DoubleValue percent(ForgeConfigSpec.Builder b, String name, double value) { return b.comment("Percentage value.").defineInRange(name, value, -100.0, 1000.0); }
    private static ForgeConfigSpec.DoubleValue seconds(ForgeConfigSpec.Builder b, String name, double value) { return b.comment("Duration in seconds.").defineInRange(name, value, 0.0, 3600.0); }
    private static ForgeConfigSpec.DoubleValue value(ForgeConfigSpec.Builder b, String name, double value, double min, double max) { return b.defineInRange(name, value, min, max); }
    public static int ticks(ForgeConfigSpec.DoubleValue seconds) { return Math.max(0, (int)Math.round(seconds.get() * 20.0)); }
    public static int ticksValue(double seconds) { return Math.max(0, (int)Math.round(seconds * 20.0)); }
}
